In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
things_dataset_original = pd.read_csv("C:\\Users\\Luka\\Documents\\Projects\\quine-llm\\_images-metadata_things.tsv", sep="\t")

things_dataset = things_dataset_original.copy()

In [17]:
things_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 27961 entries, 0 to 27960
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   index                              27961 non-null  int64
 1   image                              27961 non-null  str
 2   Word                               27961 non-null  str
 3   uniqueID                           27961 non-null  str
 4   display_label                      27961 non-null  str
 5   recognizability_answer             27961 non-null  str
 6   recognizability_RT                 27961 non-null  str
 7   recognizability_N-ratings          27961 non-null  int64
 8   recognizability_N-correct          27961 non-null  int64
 9   recognizability_N-most-common      27961 non-null  int64
 10  recognizability_most-common-label  27961 non-null  str
 11  recognizability                    27961 non-null  float64
 12  recognizability_homonyms           27961 non-null  float64
 13  recognizability_close              27961 non-null  float64
 14  nameability_N-ratings              26107 non-null  float64
 15  nameability_alternative-label      5718 non-null   str
 16  nameability_label1                 26107 non-null  str
 17  nameability_label1_moreEdit        26107 non-null  str
 18  nameability_label2                 20449 non-null  str
 19  nameability_most-frequent-rating   26107 non-null  str
 20  nameability_naming-consistency     26107 non-null  float64
 21  nameability                        26107 non-null  float64
 22  nameability_SE                     26107 non-null  float64
 23  nameability_SE-naming-consistency  26107 non-null  float64
 24  memorability_cr                    26106 non-null  float64
dtypes: float64(9), int64(4), str(12)
memory usage: 5.3 MB

In [18]:
things_dataset.sample(50)

,index,image,Word,uniqueID,display_label,recognizability_answer,recognizability_RT,recognizability_N-ratings,recognizability_N-correct,recognizability_N-most-common,...,nameability_alternative-label,nameability_label1,nameability_label1_moreEdit,nameability_label2,nameability_most-frequent-rating,nameability_naming-consistency,nameability,nameability_SE,nameability_SE-naming-consistency,memorability_cr
9351,9351,funnel/funnel_06s.jpg,funnel,funnel,funnel,"funnel, funnel, funnel, funnel, funnel, funnel...","7855, 22857, 12056, 3176, 3037, 16968, 9551 60...",14,14,14,...,NaN,",,funnel, funnel, funnel, funnel, funnel, funn...","funnel, funnel, funnel, funnel, funnel, funnel...",filter,funnel,0.941176,0.941176,0.057067,0.057067,0.644444
27896,27896,water_filter.jpg,water filter,water_filter,water filter,"water heater, water filter, heater, water filt...","8678, 9950, 5073, 26617, 8800, 19276, 8207, 72...",14,10,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20674,20674,skirt/skirt_10s.jpg,skirt,skirt,skirt,"skirt, skirt, dress, skirt, skirt, skirt, skir...","4211, 12773 3560, 4222, 13766, 25348, 8061, 60...",16,11,11,...,NaN,"skirt, skirt, skirt, skirt, skirt, skirt, skir...","skirt, skirt, skirt, skirt, skirt, skirt, skir...",woman,skirt,0.944444,0.944444,0.053990,0.053990,0.725000
16368,16368,pepper_mill/pepper_mill_14s.jpg,pepper mill,pepper_mill,pepper mill,"chessboard, bamboo, saltshaker, pepper mill, g...","8558, 73461, 10068, 8257 10817, 20236 12078 65...",16,1,8,...,"pepper mill, pepper-mill, peppermill","black pepper crusher, chess pieces, grinder, p...","black pepper crusher, chess pieces, grinder, p...",grinder,pepper grinders,0.250000,0.250000,0.096825,0.096825,0.659091
26543,26543,cream.jpg,cream,cream,cream (cosmetics),"cream (cosmetics), cream (cosmetics), cream (c...","3990, 4453, 10954, 4387, 3288, 5387, 5377, 139...",10,8,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946,1946,binder/binder_13s.jpg,binder,binder,binder,"binder, file (tool), folder, binder, file (car...","6985, 6214, 5791, 5402, 4918, 4094, 3983, 3654...",17,5,5,...,NaN,"binder, binder, binder, binder, binder, binder...","binder, binder, binder, binder, binder, binder...",pencil,binder,0.833333,0.833333,0.087841,0.087841,0.550000
3868,3868,canoe/canoe_09s.jpg,canoe,canoe,canoe,"canoe, canoe, canoe, canoe, boat, boat, boat, ...","2828, 11594, 6026, 8683, 5522, 4774, 20220, 17...",15,7,8,...,NaN,"canoe, canoe, canoe, canoe, canoe, canoe, cano...","canoe, canoe, canoe, canoe, canoe, canoe, cano...",water,canoe,0.894737,0.894737,0.070406,0.070406,0.756098
27458,27458,sand.jpg,sand,sand,sand,"sand, dessert, sand, sand, sand, sand, sand, s...","4919, 214198, 6576, 114032, 2702, 8842, 8210, ...",15,13,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4436,4436,champagne/champagne_02s.jpg,champagne,champagne,champagne,"champagne, drink, champagne, glass (drinking g...","20086, 3644, 4773, 4069, 5996, 3456 8610, 9974...",17,4,6,...,NaN,"champagne, champagne, champagne, champagne, ch...","champagne, champagne, champagne, champagne, ch...",passport,champagne,0.600000,0.600000,0.109545,0.109545,0.718590
6675,6675,cup/cup_04s.jpg,cup,cup,cup,"cup, cupcake, cup, cup, mug, teacup, cup, mug,...","3814, 2885, 5295, 6445, 7674, 12173, 4878, 470...",14,9,9,...,NaN,"coffee mug, cup, cup, cup, cup, cup, cup, cup,...","coffee mug, cup, cup, cup, cup, cup, cup, cup,...",countertop,mug,0.555556,0.388889,0.114904,0.117121,0.850000
44,44,acorn/acorn_03s.jpg,acorn,acorn,acorn,"acorn, acorn, acorn, acorn, acorn, leaf, acorn...","3197, 13207, 7786, 6991, 5076, 6744, 23494 602...",11,8,8,...,NaN,"acorn, acorn, acorn, acorn, acorn, acorn, acor...","acorn, acorn, acorn, acorn, acorn, acorn, acor...",leaf,acorn,0.944444,0.944444,0.053990,0.053990,0.875000
3234,3234,bulldozer/bulldozer_02s.jpg,bulldozer,bulldozer,bulldozer,"bulldozer, bulldozer, caterpillar, yoke (plowi...","3039, 15494, 50613, 15211 50407, 4115, 5849 35...",16,9,9,...,NaN,"bulldozer, bulldozer, bulldozer, bulldozer, bu...","bulldozer, bulldozer, bulldozer, bulldozer, bu...",hills,bulldozer,0.650000,0.650000,0.106654,0.106654,0.714286
19522,19522,scallop/scallop_10s.jpg,scallop,scallop,scallop,"dish (food), shrimp, bun (bread), dish (food),...","7283, 86347, 11862, 25030, 41303, 8203, 10955,...",14,2,8,...,NaN,"grilled seafood, scallop, scallop, scallop, sc...","grilled seafood, scallop, scallop, scallop, sc...",shrimp,seafood,0.277778,0.222222,0.097991,0.105572,0.800000
26636,26636,duffel_bag.jpg,duffel bag,duffel_bag,duffel bag,"purse, bag, purse, bag, bag, bag, bag, bag, ba...","8675, 3628, 2947, 5877, 4678, 5564, 13055, 669...",13,0,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8901,8901,float/float_02s.jpg,float,float,float,"float, swimming pool, pizza, pizza, swimming p...","20610, 4289, 15838, 16309, 4147, 102826, 10378...",18,4,9,...,NaN,"float, float, float, float, float, float, floa...","float, float, float, float, float, float, floa...",pool,float,0.812500,0.812500,0.097578,0.097578,0.780488
25883,25883,wrap/wrap_14s.jpg,wrap,wrap,wrap (food),"wrap (food), pita, pizza, wrap (food), dish (f...","4387, 18757, 5677, 5102, 4830, 3950, 38782, 35...",11,5,5,...,NaN,"burrito, burrito, burrito, sandwich roll ups, ...","burrito, burrito, burrito, sandwich roll ups, ...",table,wrap,0.789474,0.789474,0.093529,0.093529,0.794872
22222,22222,stretcher/stretcher_11s.jpg,stretcher,stretcher,stretcher,"stretcher, bed, gurney, stretcher, cot, stretc...","2771, 41805, 8676, 7068 64878, 8991, 35527, 59...",13,8,8,...,NaN,"cot, cot, gurney, gurney, stretcher, stretcher...","cot, cot, gurney, gurney, stretcher, stretcher...",NaN,stretcher,0.750000,0.750000,0.096825,0.096825,0.763158
17115,17115,plum/plum_12s.jpg,plum,plum,plum,"plum, plum, fruit, grape, fruit, grape, bluebe...","5638, 46141, 7078, 4266 7990, 5807, 6410 20195...",18,8,8,...,NaN,"berry, blueberry, grape, grape, grape, grape, ...","berry, blueberry, grape, grape, grape, grape, ...",vine,grape,0.470588,0.411765,0.119365,0.121058,0.853659
2188,2188,blindfold/blindfold_10s.jpg,blindfold,blindfold,blindfold,"blindfold, mask, blindfold, girl, blindfold, m...","5189, 20863, 20011, 75728, 2867, 107158, 4848,...",15,7,7,...,NaN,"blind folded, blindfold, blindfold, blindfold,...","blind folded, blindfold, blindfold, blindfold,...",fold eye,blindfold,0.705882,0.705882,0.110510,0.110510,0.825000
12689,12689,lab_coat/lab_coat_12s.jpg,lab coat,lab_coat,lab coat,"jersey, shirt, lab coat, lab coat, coat, lab c...","113915 13507, 3524 7530, 6021 7474, 9630, 3623...",19,8,8,...,"lab coat, lab-coat, labcoat","coat, coat, doctors coat, lab coat, lab coat, ...","coat, coat, doctors coat, lab coat, lab coat, ...",door,lab coat,0.777778,0.777778,0.097991,0.097991,0.900000
10497,10497,gyro/gyro_11s.jpg,gyro,gyro,gyro,"dish (food), wrap (food), gyro, taco, gyro, fa...","6696, 6999 6332, 7799, 4718, 8556, 82778, 4817...",9,3,3,...,NaN,"burrito, fajita, food, gyro, gyro, gyro, gyro,...","burrito, fajita, food, gyro, gyro, gyro, gyro,...",food,gyro,0.470588,0.470588,0.121058,0.121058,0.809524
12229,12229,juice/juice_03s.jpg,juice,juice,juice,"juice, juice, juice, juice, juice, juice, juic...","6504, 9726, 2697, 67302, 4980, 4618 4125, 9397...",14,12,12,...,NaN,"beverage, drink, juice, juice, juice, juice, j...","beverage, drink, juice, juice, juice, juice, j...",glasses,juice,0.894737,0.894737,0.070406,0.070406,0.785714
18429,18429,recliner/recliner_12s.jpg,recliner,recliner,recliner,"sofa bed, chair, recliner, sofa bed, sofa bed,...","4901 22691, 15414, 7222, 5532, 3214, 8794, 111...",12,4,6,...,NaN,"arm chair, armchair, chair, lazy boy, recliner...","arm chair, armchair, chair, lazy boy, recliner...",lamp,recliner,0.650000,0.650000,0.106654,0.106654,0.666667
17612,17612,power_line/power_line_11s.jpg,power line,power_line,power line,"wire, power line, telephone pole, wire, power ...","4144 52180, 5481 63886, 84833, 8985, 6402, 487...",14,7,7,...,"power line, power-line, powerline","electric wire, electrical lines, electrical wi...","electric wire, electrical lines, electrical wi...",sky,power line,0.444444,0.500000,0.117851,0.117121,0.731707
15109,15109,noodle/noodle_05s.jpg,noodle,noodle,noodle,"spaghetti, noodle, noodle, food processor, noo...","67683, 7780, 10008, 4588 5845, 6899, 10009, 44...",14,9,9,...,NaN,"noodle, noodle, noodle, noodle, noodle, noodle...","noodle, noodle, noodle, noodle, noodle, noodle...",green onions,noodle,0.833333,0.833333,0.087841,0.087841,0.710526
17443,17443,popsicle/popsicle_04s.jpg,popsicle,popsicle,popsicle,"ice cream, ice, ice, popsicle, ice cream, ice ...","2664 15937, 17391, 3660, 3273, 27715, 13527, 1...",19,3,10,...,NaN,"ice pop, popsicle, popsicle, popsicle, popsicl...","ice pop, popsicle, popsicle, popsicle, popsicl...",popsicle stick,popsicle,0.894737,0.894737,0.070406,0.070406,0.894737
17306,17306,polisher/polisher_11s.jpg,polisher,polisher,polisher (buffing machine),"duster, blower, blower, duster, polisher (buff...","3780, 3493, 4560, 6100, 46843, 98302, 7828, 44...",12,6,6,...,NaN,"buffer, buffer, buffer, buffer, buffer, electr...","buffer, buffer, buffer, buffer, buffer, electr...",NaN,polisher,0.333333,0.333333,0.111111,0.111111,0.650000
24203,24203,trombone/trombone_03s.jpg,trombone,trombone,trombone,"trombone, trumpet, french horn, trumpet, trump...","11758, 2898, 3263, 4001, 8234, 10987 101946, 4...",18,8,8,...,NaN,"clarinet, instrument, musical instrument, trom...","clarinet, instrument, musical instrument, trom...",horn,trombone,0.500000,0.500000,0.125000,0.125000,0.780488
23143,23143,telegraph/telegraph_07s.jpg,telegraph,telegraph,telegraph,"telegraph, key, record player, sewing machine,...","4026 119677, 6768, 29480, 5823, 10834, 16207, ...",15,9,9,...,NaN,"honestly, machine, morris code, morse code mac...","honestly, machine, morris code, morse code mac...",wooden surface,telegraph,0.500000,0.500000,0.111803,0.111803,0.710526
9711,9711,glass/glass_05s.jpg,glass,glass,glass (drinking glass),"glass (drinking glass), glass (drinking glass)...","9354, 3238, 18174, 3836, 4620, 4872, 309905, 7...",21,21,21,...,NaN,"glass, glass, glass, glass, glass, glass, glas...","glass, glass, glass, glass, glass, glass, glas...",table,glass,1.000000,1.000000,0.000000,0.000000,0.692308
13474,13474,log/log_08s.jpg,log,log,log,"wood, wood, log, wood, tree, wood, wood, wood,...","6479, 5941, 7432, 4409, 3955, 7574, 4666, 1077...",17,5,8,...,NaN,"log, log, log, log, log, log, log, log, log, l...","log, log, log, log, log, log, log, log, log, l...",grass,log,0.900000,0.900000,0.067082,0.067082,0.780488
20319,20319,shovel/shovel_06s.jpg,shovel,shovel,shovel,"trowel (garden tool), shovel, trowel (garden t...","6936, 3546, 5732, 82509, 2273, 37711, 5529 430...",12,8,8,...,NaN,"shovel, shovel, shovel, shovel, shovel, shovel...","shovel, shovel, shovel, shovel, shovel, shovel...",NaN,shovel,0.888889,0.888889,0.074074,0.074074,0.829268
14772,14772,mug/mug_01b.jpg,mug,mug,mug,"cup, mug, cup, cup, mug, cup, mug, cup, mug, m...","7412, 5626, 2969, 6164, 3243, 9393, 3230, 4515...",16,7,9,...,NaN,"coffee cup, coffee cup, cuo, mug, mug, mug, mu...","coffee cup, coffee cup, cuo, mug, mug, mug, mu...",NaN,mug,0.833333,0.833333,0.087841,0.087841,0.700000
304,304,amplifier/amplifier_16s.jpg,amplifier,amplifier,amplifier,"speaker, radio, speaker, radio, suitcase, tape...","7072, 6121 3709, 3280, 6591, 8852, 7261, 31510...",16,4,6,...,NaN,"amplifier, amplifier, amplifier, amplifier, am...","amplifier, amplifier, amplifier, amplifier, am...",NaN,amplifier,0.888889,0.888889,0.074074,0.074074,0.700000
6565,6565,crystal_ball/crystal_ball_10s.jpg,crystal ball,crystal_ball,crystal ball,"crystal ball, crystal ball, paperweight, cryst...","286208, 5296, 5074, 4137, 7631, 9384, 3440, 28...",14,5,5,...,"crystal ball, crystal-ball, crystalball","bead, crystal ball, droplet, glass ball, glass...","bead, crystal ball, droplet, glass ball, glass...",trees,marble,0.526316,0.052632,0.051228,0.114549,0.725000
16136,16136,peanut_butter/peanut_butter_10s.jpg,peanut butter,peanut_butter,peanut butter,"peanut butter, peanut butter, peanut butter, p...","35386, 4454, 3460, 18698 5796, 12606, 14726, 4...",12,9,9,...,"peanut butter, peanut-butter, peanutbutter","bowl, food, food, peanut butter, peanut butter...","bowl, food, food, peanut butter, peanut butter...",peanuts,peanut butter,0.850000,0.850000,0.079844,0.079844,0.794872
2198,2198,block/block_02s.jpg,block,block,block,"block, block, block, block, jigsaw puzzle, gam...","4481, 4173, 5086, 10591, 91742, 5327 99507, 66...",16,10,10,...,NaN,"block, block, block, block, block, block, bloc...","block, block, block, block, block, block, bloc...",road,block,0.947368,0.947368,0.051228,0.051228,0.731707
7989,7989,eggnog/eggnog_12s.jpg,eggnog,eggnog,eggnog,"milkshake, latte, glass (drinking glass), milk...","4486, 8862, 11786, 9484, 5974, 19353, 7289 526...",12,3,4,...,NaN,"beverage, beverage, candle, candle, drink, egg...","beverage, beverage, candle, candle, drink, egg...",cinnamon stick,eggnog,0.631579,0.631579,0.110665,0.110665,0.857143
5870,5870,cord/cord_13s.jpg,cord,cord,cord,"cable, cable, cord, cord, cord, cord, wire, co...","11430, 4025, 18606, 4365 4112, 3406, 2287, 840...",14,5,5,...,NaN,"cable, cable wire, charge, cord, cord, cord, c...","cable, cable wire, charge, cord, cord, cord, c...",NaN,cord,0.705882,0.705882,0.110510,0.110510,0.804878
26534,26534,coyote.jpg,coyote,coyote,coyote,"hyena, coyote, fox, fox, wolf, coyote, fox, co...","7350 4301, 14199 3498, 6752, 9558, 4159, 3779,...",18,6,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3665,3665,camera1/camera1_01b.jpg,camera,camera1,camera (photos),"camera (photos), camera (photos), camera (phot...","7408, 8081, 5896, 6032, 6224, 4399, 58641, 534...",11,9,9,...,NaN,"camera, camera, camera, camera, camera, camera...","camera, camera, camera, camera, camera, camera...",lens,camera,1.000000,1.000000,0.000000,0.000000,0.750000
14426,14426,mold1/mold1_01b.jpg,mold,mold1,mold (form),"mold (form), mold (form), pan, mold (form), mo...","7468, 28346 6771, 6347, 9712 24283, 7391, 1551...",16,12,12,...,NaN,"bundt pan, cake form, cookie tins, cookie tray...","bundt pan, cake form, cookie tins, cookie tray...",NaN,mold,0.421053,0.421053,0.113269,0.113269,0.714286
16055,16055,patty/patty_13s.jpg,patty,patty,patty,"cake, chicken (meat), hamburger, dish (food), ...","4862, 18520, 8467 6134, 6640, 9699, 8643 15747...",14,2,4,...,NaN,"burger, burger patties, burger patties, burger...","burger, burger patties, burger patties, burger...",tissue,burger patties,0.473684,0.210526,0.093529,0.114549,0.829268
5580,5580,collar/collar_01b.jpg,collar,collar,collar,"bell, collar, belt, collar, belt, belt, collar...","6187, 137840, 8902, 5059, 11474, 8015, 4448, 5...",13,5,6,...,NaN,"belt, collar, collar, collar, collar, collar, ...","belt, collar, collar, collar, collar, collar, ...",NaN,collar,0.937500,0.937500,0.060515,0.060515,0.775610
10309,10309,groundhog/groundhog_12n.jpg,groundhog,groundhog,groundhog,"margarita, rat, rat, marmalade, rat, groundhog...","97597, 30466, 59836, 33407, 6515, 23400, 10308...",15,3,4,...,NaN,"badget, beaver, beaver, beaver, gopher, gopher...","badget, beaver, beaver, beaver, gopher, gopher...",rock,groundhog,0.368421,0.368421,0.110665,0.110665,0.526316
90,90,air_pump/air_pump_07s.jpg,air pump,air_pump,air pump,"pump, air pump, air pump, air pump, pump, pump...","11758, 11265, 6445 9026, 19092, 22682, 26582, ...",18,11,11,...,"air pump, air-pump, airpump","air filler, air pump, air pump, air pump, air ...","air filler, air pump, air pump, air pump, air ...",air pump,air pump,0.250000,0.250000,0.096825,0.096825,0.761905
23557,23557,toe/toe_05s.jpg,toe,toe,toe,"leg, finger, toe, foot, toe, toe, foot, toe, b...","6803, 5459, 3597, 23797, 12423, 9740, 3911, 89...",18,7,7,...,NaN,"baby feet, baby feet, baby feet, blanket, foot...","baby feet, baby feet, baby feet, blanket, foot...",feet,toe,0.588235,0.588235,0.119365,0.119365,0.833333
4010,4010,cardboard/cardboard_07s.jpg,cardboard,cardboard,cardboard,"cardboard, cardboard, cardboard, cardboard, ca...","8652 7163, 3170, 12305, 8024, 28408, 5738, 715...",14,12,12,...,NaN,"box, box, cardboard, cardboard, cardboard, car...","box, box, cardboard, cardboard, cardboard, car...",ridges,cardboard,0.823529,0.823529,0.092459,0.092459,0.761905
14434,14434,mold1/mold1_09s.jpg,mold,mold1,mold (form),"clay, chocolate, silicone, chocolate, chocolat...","13852, 4547, 24995, 9334, 6305, 5400, 6713, 60...",14,3,4,...,NaN,"cake pan, chocolate, chocolate bar, kaka emoji...","cake pan, chocolate, chocolate bar, kaka emoji...",poop emoji,mold,0.777778,0.777778,0.097991,0.097991,0.829268
17082,17082,pliers/pliers_07s.jpg,pliers,pliers,pliers,"tool, wrench, wire cutters, pliers, tool, plie...","3497, 9101, 58691, 9255, 6275, 2687, 57838, 15...",14,4,4,...,multi-tool,"clamp, forceps, pliers, pliers, pliers, pliers...","clamp, forceps, pliers, pliers, pliers, pliers...",NaN,pliers,0.611111,0.611111,0.114904,0.114904,0.868421

In [19]:
things_dataset.head(20)

,index,image,Word,uniqueID,display_label,recognizability_answer,recognizability_RT,recognizability_N-ratings,recognizability_N-correct,recognizability_N-most-common,...,nameability_alternative-label,nameability_label1,nameability_label1_moreEdit,nameability_label2,nameability_most-frequent-rating,nameability_naming-consistency,nameability,nameability_SE,nameability_SE-naming-consistency,memorability_cr
0,0,aardvark/aardvark_01b.jpg,aardvark,aardvark,aardvark,"aardvark, kangaroo, aardvark, aardvark, aardva...","6062 7496, 17134 18443, 42413, 4302 11470, 549...",15,10,10,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",sand,aardvark,0.411765,0.411765,0.119365,0.119365,0.825000
1,1,aardvark/aardvark_02s.jpg,aardvark,aardvark,aardvark,"aardvark, anteater, anteater, pig, aardvark, c...","73673, 5546, 5014, 5893, 22285, 41335, 7026, 1...",11,4,4,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",dirt,anteater,0.500000,0.400000,0.109545,0.111803,0.800000
2,2,aardvark/aardvark_03s.jpg,aardvark,aardvark,aardvark,"pig, aardvark, aardvark, kangaroo, donkey, aar...","4785, 1920, 11164, 26083, 10230, 17653, 35548,...",13,8,8,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",straw,aardvark,0.333333,0.333333,0.111111,0.111111,0.878049
3,3,aardvark/aardvark_04s.jpg,aardvark,aardvark,aardvark,"anteater, rabbit, anteater, aardvark, pig, ant...","3314, 6581, 11938, 4066, 4792, 4377, 46142, 16...",16,7,7,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",grass,anteater,0.588235,0.411765,0.119365,0.119365,0.731707
4,4,aardvark/aardvark_05s.jpg,aardvark,aardvark,aardvark,"aardvark, aardvark, bat (animal), aardvark, aa...","35661, 37730, 11795, 27933, 18876 12792, 39915...",18,13,13,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",NaN,anteater,0.444444,0.333333,0.111111,0.117121,0.825000
5,5,aardvark/aardvark_06s.jpg,aardvark,aardvark,aardvark,"pig, bat (animal), aardvark, aardvark, aardvar...","11182, 9533 6517, 13300, 28134 5703, 40779, 63...",15,6,6,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",NaN,aardvark,0.250000,0.250000,0.096825,0.096825,0.619048
6,6,aardvark/aardvark_07s.jpg,aardvark,aardvark,aardvark,"aardvark, calf (animal), pig, cage (animals), ...","23932, 30687, 5394, 9470, 35407, 28583, 3588, ...",13,7,7,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",grass,aardvark,0.368421,0.368421,0.110665,0.110665,0.722222
7,7,aardvark/aardvark_08s.jpg,aardvark,aardvark,aardvark,"aardvark, bat (animal), aardvark, cage (animal...","19239, 3472, 27654, 8515, 3442, 143785, 65685,...",15,8,8,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",building,anteater,0.421053,0.368421,0.110665,0.113269,0.794872
8,8,aardvark/aardvark_09s.jpg,aardvark,aardvark,aardvark,"anteater, aardvark, aardvark, anteater, anteat...","3493, 16454, 11917, 3851, 4032, 6296, 5704, 14...",14,4,8,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",ground,anteater,0.578947,0.263158,0.101023,0.113269,0.750000
9,9,aardvark/aardvark_10s.jpg,aardvark,aardvark,aardvark,"elephant, hippopotamus, aardvark, anteater, aa...","7877, 30455, 10619, 5161, 52129, 4806, 7817, 2...",15,5,5,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",grass,anteater,0.421053,0.368421,0.110665,0.113269,0.809524
10,10,aardvark/aardvark_11s.jpg,aardvark,aardvark,aardvark,"pig, aardvark, anteater, anteater, anteater, p...","17893, 38962, 7207, 3570, 5517, 6381, 23542, 2...",13,5,5,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",grass,aardvark,0.500000,0.500000,0.117851,0.117851,0.815789
11,11,aardvark/aardvark_12s.jpg,aardvark,aardvark,aardvark,"aardvark, aardvark, anteater, aardvark, anteat...","10717, 61993, 6226, 13618, 11199, 2689, 9526, ...",13,7,7,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",sand,aardvark,0.500000,0.500000,0.117851,0.117851,0.837209
12,12,aardvark/aardvark_13s.jpg,aardvark,aardvark,aardvark,"aardvark, anteater, aardvark, aardvark, aardva...","22371, 5487, 13699, 35899, 23577, 15201, 15074...",13,7,7,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",NaN,anteater,0.500000,0.333333,0.111111,0.117851,0.682927
13,13,aardvark/aardvark_14s.jpg,aardvark,aardvark,aardvark,"aardvark, anteater, aardvark, anteater, anteat...","6669, 8860, 9319, 3310, 3769, 7387, 4354, 4909...",15,5,9,...,NaN,"aardvark, aardvark, aardvark, aardvark, aardva...","aardvark, aardvark, aardvark, aardvark, aardva...",grass,anteater,0.666667,0.277778,0.105572,0.111111,0.825000
14,14,abacus/abacus_01b.jpg,abacus,abacus,abacus,"abacus, abacus, abacus, calculator, abacus, ab...","10543, 3933, 3614, 14878, 14142, 5161, 10363, ...",14,12,12,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",floor,abacus,0.500000,0.500000,0.111803,0.111803,0.648649
15,15,abacus/abacus_02s.jpg,abacus,abacus,abacus,"abacus, abacus, applesauce, abacus, abacus, co...","15218, 6376, 6620, 9754, 4455 7595, 3637, 1109...",13,10,10,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",red cloth,abacus,0.944444,0.944444,0.053990,0.053990,0.785714
16,16,abacus/abacus_03s.jpg,abacus,abacus,abacus,"abacus, abacus, abacus, playing card, kilt, ab...","3326, 4082, 7307, 27906, 9169, 2325, 9330, 368...",13,10,10,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",arm,abacus,0.842105,0.842105,0.083655,0.083655,0.780488
17,17,abacus/abacus_04s.jpg,abacus,abacus,abacus,"rack (stand), abacus, abacus, abacus, game, to...","112054, 28981, 48492, 3395, 17614, 7793, 1961,...",19,12,12,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",NaN,abacus,0.777778,0.777778,0.097991,0.097991,0.825000
18,18,abacus/abacus_05s.jpg,abacus,abacus,abacus,"abacus, abacus, abacus, abacus, abacus, abacus...","22163 11799, 10155, 3138, 5157, 2479, 4386, 29...",10,9,9,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",child,abacus,0.833333,0.833333,0.087841,0.087841,0.878049
19,19,abacus/abacus_06s.jpg,abacus,abacus,abacus,"abacus, abacus, abacus, abacus, abacus, abacus...","11870, 3277, 3109, 25133, 62795, 5070, 2102, 2...",11,11,11,...,NaN,"abacus, abacus, abacus, abacus, abacus, abacus...","abacus, abacus, abacus, abacus, abacus, abacus...",beads,abacus,0.764706,0.764706,0.102879,0.102879,0.897436

In [20]:
# Find 50 concepts from the dataset each having higher naming consistency, start from the concept with the lowest consistency in the dataset and end with the highest consistency,
# make it so that each concept has a proportionately higher naming consistency than the previous one, ending with the concept having the highest consistency,
# do not use entries with the same naming consistency, each selected concept should have a unique naming consistency value
# Nan values are excluded from the selection
# Since each word has several rows which represent different images presented to participants, we need to make sure that naming consistency is 
# calculated as the average naming consistency across all images for each word

def get_top_50_concepts(things_dataset):
    
    things_dataset = things_dataset.copy()

    things_dataset = things_dataset.dropna(subset=["nameability_naming-consistency"])

    things_dataset = things_dataset.groupby("Word", as_index=False)["nameability_naming-consistency"].mean()

    sorted_things = things_dataset.sort_values(by="nameability_naming-consistency")
    top_50_concepts = sorted_things.iloc[::len(sorted_things)//50, :].head(50)
    
    return top_50_concepts

get_top_50_concepts(things_dataset)

                 Word  nameability_naming-consistency
767        hobbyhorse                        0.193307
1230           pulpit                        0.323002
1107            patty                        0.361923
1818             yoke                        0.381875
395       cordon bleu                        0.398982
711           gumdrop                        0.417929
1656       tortellini                        0.437276
640           garbage                        0.453328
1253              rag                        0.470846
1068           outfit                        0.486130
298           charger                        0.497988
1213           potpie                        0.509621
1568         swimsuit                        0.531087
357         coat rack                        0.546212
1049              oar                        0.560762
348           clothes                        0.572765
1301           roller                        0.588570
796            hummus                        0.598567
440           crystal                        0.606806
1557          sunroof                        0.620461
1799              wok                        0.634704
1515    station wagon                        0.648714
1801            woman                        0.660846
851            kettle                        0.677771
400         cornbread                        0.693249
407               cot                        0.702504
1031           napkin                        0.719486
635          fur coat                        0.732056
449      curling iron                        0.743979
1270  rearview mirror                        0.761066
496       doorknocker                        0.771653
122            binder                        0.784184
1807   wrapping paper                        0.797005
584     first-aid kit                        0.808528
795       hummingbird                        0.823666
1358            scoop                        0.835471
462              deer                        0.848857
539    electric chair                        0.859749
7              airbag                        0.872060
693            grater                        0.879297
96               bead                        0.889888
647              gate                        0.901633
177     boxing gloves                        0.911311
62             bamboo                        0.920929
439            crutch                        0.933697
924            locker                        0.945259
1534            stool                        0.954410
1059           orange                        0.961524
782             horse                        0.970854
953               map                        0.980343

In [21]:
list_of_top_50_concepts = get_top_50_concepts(things_dataset)["Word"].tolist()

with open("C:\\Users\\Luka\\Documents\\Projects\\quine-llm\\list_of_top_50_concepts.txt", "w") as f:
    for concept in list_of_top_50_concepts:
        f.write(f"{concept}\n")
        
# What does the above code do?

# The above code retrieves the top 50 concepts from the dataset based on naming consistency, stores them in a list, and writes them to a text file.

# Where to find the txt file
# The text file "list_of_top_50_concepts.txt" will be saved in "C:\Users\Luka\Documents\Projects\quine-llm\".

# Can't find the text file? Make sure to check the current working directory.

#

In [22]:
list_of_top_50_concepts

['hobbyhorse',
 'pulpit',
 'patty',
 'yoke',
 'cordon bleu',
 'gumdrop',
 'tortellini',
 'garbage',
 'rag',
 'outfit',
 'charger',
 'potpie',
 'swimsuit',
 'coat rack',
 'oar',
 'clothes',
 'roller',
 'hummus',
 'crystal',
 'sunroof',
 'wok',
 'station wagon',
 'woman',
 'kettle',
 'cornbread',
 'cot',
 'napkin',
 'fur coat',
 'curling iron',
 'rearview mirror',
 'doorknocker',
 'binder',
 'wrapping paper',
 'first-aid kit',
 'hummingbird',
 'scoop',
 'deer',
 'electric chair',
 'airbag',
 'grater',
 'bead',
 'gate',
 'boxing gloves',
 'bamboo',
 'crutch',
 'locker',
 'stool',
 'orange',
 'horse',
 'map']

In [23]:
# Take all rows in the dataset where the "Word" column contains "crystal", 
# there should be 3 different 'crystal' entries,
# and show the average of the naming consistency for each of those entries

things_dataset.loc[things_dataset["Word"].str.contains("crystal", case=False, na=False)].groupby("Word")["nameability_naming-consistency"].mean()

Word
crystal         0.606806
crystal ball    0.370347
Name: nameability_naming-consistency, dtype: float64

In [24]:
# Show all rows in the dataset where the "Word" column contains "crystal"

things_dataset.loc[things_dataset["Word"].str.contains("crystal", case=False, na=False)]

,index,image,Word,uniqueID,display_label,recognizability_answer,recognizability_RT,recognizability_N-ratings,recognizability_N-correct,recognizability_N-most-common,...,nameability_alternative-label,nameability_label1,nameability_label1_moreEdit,nameability_label2,nameability_most-frequent-rating,nameability_naming-consistency,nameability,nameability_SE,nameability_SE-naming-consistency,memorability_cr
6556,6556,crystal_ball/crystal_ball_01b.jpg,crystal ball,crystal_ball,crystal ball,"crystal ball, crystal ball, crystal ball, magn...","3944, 7827, 7781, 26610, 14270, 24969, 14433, ...",19,8,8,...,"crystal ball, crystal-ball, crystalball","alabaster, alabaster, alabaster, bell, crystal...","alabaster, alabaster, alabaster, bell, crystal...",wood base,crystal ball,0.473684,0.473684,0.114549,0.114549,0.575000
6557,6557,crystal_ball/crystal_ball_02s.jpg,crystal ball,crystal_ball,crystal ball,"crystal ball, crystal ball, crystal ball, glob...","23172, 18404, 4637, 4332, 13782, 4264, 11019, ...",15,9,9,...,"crystal ball, crystal-ball, crystalball","crystal ball, crystal ball, crystal ball, crys...","crystal ball, crystal ball, crystal ball, crys...",pedestal,crystal ball,0.736842,0.736842,0.101023,0.101023,0.780488
6558,6558,crystal_ball/crystal_ball_03s.jpg,crystal ball,crystal_ball,crystal ball,"crystal ball, ball, ballot box, ball, crystal ...","39929, 26120, 9183, 7326, 12624 29892, 20203, ...",11,6,6,...,"crystal ball, crystal-ball, crystalball","ball, ball, ball, ball, ball, christmas orname...","ball, ball, ball, ball, ball, christmas orname...",hand,ball,0.263158,0.105263,0.070406,0.101023,0.761905
6559,6559,crystal_ball/crystal_ball_04s.jpg,crystal ball,crystal_ball,crystal ball,"ball, pearl, globe (spinning globe), globe (sp...","64664, 6057, 4340 15997, 4485, 4459, 8788, 148...",13,5,5,...,"crystal ball, crystal-ball, crystalball","ball, crystal ball, crystal ball, crystal ball...","ball, crystal ball, crystal ball, crystal ball...",stand,globe,0.333333,0.166667,0.087841,0.111111,0.727273
6560,6560,crystal_ball/crystal_ball_05s.jpg,crystal ball,crystal_ball,crystal ball,"marble, crystal ball, crystal ball, crystal ba...","12199, 5129, 45986, 14076, 9446, 98142, 35932,...",12,5,5,...,"crystal ball, crystal-ball, crystalball","bubble, crystal, glass, glass ball, glass ball...","bubble, crystal, glass, glass ball, glass ball...",moss,marble,0.333333,0.000000,0.000000,0.111111,0.725000
6561,6561,crystal_ball/crystal_ball_06s.jpg,crystal ball,crystal_ball,crystal ball,"mirror, crystal ball, crystal ball, magnifying...","7314, 6796, 25782, 106764, 12150, 3419, 41795,...",15,5,5,...,"crystal ball, crystal-ball, crystalball",",,ball, crystal ball, crystal ball, crystal ba...",",,ball, crystal ball, crystal ball, crystal ba...",stand,crystal ball,0.277778,0.277778,0.105572,0.105572,0.658537
6562,6562,crystal_ball/crystal_ball_07s.jpg,crystal ball,crystal_ball,crystal ball,"marble, crystal ball, marble, ball, ball, mirr...","13394, 83060, 12264, 10678, 3849, 31236, 36505...",8,3,3,...,"crystal ball, crystal-ball, crystalball","ball, crystal sphere, glass ball, glass ball, ...","ball, crystal sphere, glass ball, glass ball, ...",rocks,marble,0.352941,0.000000,0.000000,0.115904,0.731707
6563,6563,crystal_ball/crystal_ball_08s.jpg,crystal ball,crystal_ball,crystal ball,"palette, crystal ball, crystal ball, marble, b...","6454, 27440, 5248, 9676, 21735, 3383 90852 314...",14,6,6,...,"crystal ball, crystal-ball, crystalball","crystal ball, dome, gazing ball, gazing ball, ...","crystal ball, dome, gazing ball, gazing ball, ...",glass,marble,0.400000,0.066667,0.064406,0.126491,0.550000
6564,6564,crystal_ball/crystal_ball_09s.jpg,crystal ball,crystal_ball,crystal ball,"mirror, crystal ball, marble, mirror, crystal ...","10797, 24598, 19417, 15365, 70329, 6673, 6808,...",13,4,4,...,"crystal ball, crystal-ball, crystalball","clear glass sphere, crystal, crystal ball, cry...","clear glass sphere, crystal, crystal ball, cry...",landscape,glass ball,0.200000,0.100000,0.067082,0.089443,0.634146
6565,6565,crystal_ball/crystal_ball_10s.jpg,crystal ball,crystal_ball,crystal ball,"crystal ball, crystal ball, paperweight, cryst...","286208, 5296, 5074, 4137, 7631, 9384, 3440, 28...",14,5,5,...,"crystal ball, crystal-ball, crystalball","bead, crystal ball, droplet, glass ball, glass...","bead, crystal ball, droplet, glass ball, glass...",trees,marble,0.526316,0.052632,0.051228,0.114549,0.725000
6566,6566,crystal_ball/crystal_ball_11s.jpg,crystal ball,crystal_ball,crystal ball,"marble, ball, crystal ball, crystal (rock), wa...","38323, 42766, 36395, 17197, 29527, 15321 13722...",13,3,3,...,"crystal ball, crystal-ball, crystalball","ball, clear marble, crystal ball, crystal ball...","ball, clear marble, crystal ball, crystal ball...",sand,crystal ball,0.157895,0.157895,0.083655,0.083655,0.731707
6567,6567,crystal_ball/crystal_ball_12s.jpg,crystal ball,crystal_ball,crystal ball,"tablet (electronic device), globe (spinning gl...","15893, 9550, 21209, 17791, 7257, 17769, 3700, ...",12,7,7,...,"crystal ball, crystal-ball, crystalball","ball, ball, crystal, crystal ball, crystal bal...","ball, ball, crystal, crystal ball, crystal bal...",table,crystal ball,0.388889,0.388889,0.114904,0.114904,0.650000
6568,6568,crystal1/crystal1_01b.jpg,crystal,crystal1,crystal (material),"crystal (rock), machete, needle, stained glass...","15153, 8287 15828 6255, 11221, 39041, 10615, 1...",15,3,4,...,NaN,"algae, bench, candy, coral, crystal, crystal, ...","algae, bench, candy, coral, crystal, crystal, ...",NaN,crystal,0.526316,0.526316,0.114549,0.114549,0.875000
6569,6569,crystal1/crystal1_02s.jpg,crystal,crystal1,crystal (material),"iceskate, crystal (material), crystal (rock), ...","3408, 46074, 247359, 4549, 26883, 13270, 14782...",13,2,2,...,NaN,"bowl, cellophane noodles, coconut, coconut, fl...","bowl, cellophane noodles, coconut, coconut, fl...",bowl,rice,0.277778,0.000000,0.000000,0.105572,0.850000
6570,6570,crystal1/crystal1_03s.jpg,crystal,crystal1,crystal (material),"crystal (material), cotton candy, cotton candy...","12969, 28885, 7748 13654, 20490, 5367, 12562 1...",11,4,5,...,NaN,"agar, asbestos, candy, candy floss, craft ball...","agar, asbestos, candy, candy floss, craft ball...",NaN,crystal,0.150000,0.150000,0.079844,0.079844,0.744186
6571,6571,crystal1/crystal1_04s.jpg,crystal,crystal1,crystal (material),"ice, crystal (material), crystal (rock), icepi...","4766, 13432, 24015, 8013, 62657, 16388, 37175,...",13,4,4,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",pine tree,crystal,0.588235,0.588235,0.119365,0.119365,0.769231
6572,6572,crystal1/crystal1_05s.jpg,crystal,crystal1,crystal (material),"cotton candy, coal, moss, coral, dessert, leaf...","7017, 8719, 8375, 48014, 6820, 7814, 99525 484...",14,2,3,...,NaN,"colored fuzz, coral, coral, coral, coral, cora...","colored fuzz, coral, coral, coral, coral, cora...",NaN,coral,0.315789,0.105263,0.070406,0.106639,0.780488
6573,6573,crystal1/crystal1_06s.jpg,crystal,crystal1,crystal (material),"crystal (material), spaghetti, crystal (materi...","15924, 148878, 17325 11875, 9547 26134, 16648,...",11,4,4,...,NaN,"blob, candy, candy, crystal, crystal, crystal,...","blob, candy, candy, crystal, crystal, crystal,...",NaN,crystal,0.352941,0.352941,0.115904,0.115904,0.743590
6574,6574,crystal1/crystal1_07s.jpg,crystal,crystal1,crystal (material),"clay, crystal (material), rock, snowball, rock...","6928 56697, 3472, 5272, 4560, 175476, 4303, 11...",12,3,3,...,NaN,"busted tide pod, colored rock, crystal, crysta...","busted tide pod, colored rock, crystal, crysta...",hand,crystal,0.411765,0.411765,0.119365,0.119365,0.850000
6575,6575,crystal1/crystal1_08s.jpg,crystal,crystal1,crystal (material),"pom-pom, coral, moss, coral, coral, coal, cora...","3698, 2500, 44648, 4677, 7839, 154041 25878, 1...",15,0,6,...,NaN,"bliss, coral, coral, coral, coral, coral, cora...","bliss, coral, coral, coral, coral, coral, cora...",NaN,coral,0.529412,0.058824,0.057067,0.121058,0.794872
6576,6576,crystal1/crystal1_09s.jpg,crystal,crystal1,crystal (material),"iceskate, ice, ice cube, snow, crystal (materi...","6981, 14486, 49656, 25341, 25823, 7738, 10363,...",14,2,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",frost,crystal,0.500000,0.500000,0.111803,0.111803,0.888889
6577,6577,crystal1/crystal1_10s.jpg,crystal,crystal1,crystal (material),"silverware, needle, crystal (rock), magnifying...","40545, 128463 41966, 70525, 30805, 24418, 2599...",14,3,3,...,NaN,"agate, crystal, crystal, crystal, crystal, cry...","agate, crystal, crystal, crystal, crystal, cry...",NaN,crystal,0.588235,0.588235,0.119365,0.119365,0.800000
6578,6578,crystal1/crystal1_11s.jpg,crystal,crystal1,crystal (material),"crystal (rock), crystal (rock), crystal (mater...","5016, 21909, 9774, 5288, 30715, 63782, 14894, ...",16,6,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",NaN,crystal,0.650000,0.650000,0.106654,0.106654,0.736842
6579,6579,crystal1/crystal1_12s.jpg,crystal,crystal1,crystal (material),"fishbowl, bottle, crystal (material), ice, cry...","12277, 36530, 39100, 3739, 23415, 8399, 16354,...",14,6,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",rocks,crystal,0.578947,0.578947,0.113269,0.113269,0.785714
6580,6580,crystal2/crystal2_01b.jpg,crystal,crystal2,crystal (rock),"crystal (rock), crystal (rock), crystal (rock)...","5069, 8490, 10722, 66188, 6067, 4309, 41742, 5...",13,6,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",wood,crystal,0.722222,0.722222,0.105572,0.105572,0.894737
6581,6581,crystal2/crystal2_02s.jpg,crystal,crystal2,crystal (rock),"crystal (rock), crystal (rock), crystal (rock)...","6679, 10335, 23695, 15714, 8903 13804, 4133, 6...",15,9,9,...,NaN,"crysta, crystal, crystal, crystal, crystal, cr...","crysta, crystal, crystal, crystal, crystal, cr...",NaN,crystal,0.714286,0.714286,0.120736,0.120736,0.736842
6582,6582,crystal2/crystal2_03s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crystal (material), crysta...","3090, 2760, 7733, 9188, 5290, 8774, 14903, 202...",11,4,4,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",hand,crystal,0.894737,0.894737,0.070406,0.070406,0.850000
6583,6583,crystal2/crystal2_04s.jpg,crystal,crystal2,crystal (rock),"crystal (rock), ice, ice, crystal (rock), ice,...","7803, 10428 4902, 74811, 4661, 5512, 11798, 71...",15,3,6,...,NaN,"crystal, crystal, crystal, crystal, fridge, ic...","crystal, crystal, crystal, crystal, fridge, ic...",hand,ice,0.312500,0.250000,0.108253,0.115878,0.750000
6584,6584,crystal2/crystal2_05s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crystal (material), crysta...","3264 119526, 11280, 11125, 6925 2976, 3896, 73...",13,4,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",rock,crystal,0.842105,0.842105,0.083655,0.083655,0.763158
6585,6585,crystal2/crystal2_06s.jpg,crystal,crystal2,crystal (rock),"crystal (rock), crystal (material), crystal (m...","8475, 5888, 4952 6747, 32205, 29539, 91714, 53...",18,7,7,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",fingers,crystal,0.789474,0.789474,0.093529,0.093529,0.743590
6586,6586,crystal2/crystal2_07s.jpg,crystal,crystal2,crystal (rock),"crystal (material), peacock, crystal (material...","53494, 13322, 111008, 3978, 10224, 38991, 6618...",16,5,6,...,NaN,"coal, crystal, crystal, crystal, crystal, erty...","coal, crystal, crystal, crystal, crystal, erty...",hand,rock,0.300000,0.200000,0.089443,0.102470,0.878049
6587,6587,crystal2/crystal2_08s.jpg,crystal,crystal2,crystal (rock),"crystal (material), diamond, paperweight, crys...","2887, 6618, 5942, 3616, 24556, 310179 8606, 10...",15,3,5,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",table,crystal,0.631579,0.631579,0.110665,0.110665,0.750000
6588,6588,crystal2/crystal2_09s.jpg,crystal,crystal2,crystal (rock),"crystal (rock), pearl, crystal (rock), diamond...","4383, 12758, 20108, 4536 37585, 17897, 7376, 2...",14,5,5,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",hands,crystal,0.470588,0.470588,0.121058,0.121058,0.800000
6589,6589,crystal2/crystal2_10s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crystal (rock), crystal (r...","3633, 6151 4787, 10478, 75048, 6380, 19236, 42...",14,9,9,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",NaN,crystal,0.894737,0.894737,0.070406,0.070406,0.720930
6590,6590,crystal2/crystal2_11s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crystal (material), crysta...","3846, 3874, 29517 22762, 3765, 15150, 11546, 9...",14,5,5,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",hand,crystal,0.888889,0.888889,0.074074,0.074074,0.950000
6591,6591,crystal2/crystal2_12s.jpg,crystal,crystal2,crystal (rock),"marble, crystal (material), granite, crystal (...","11658, 3447, 18595, 9860, 4663 4927, 36833, 11...",17,2,6,...,NaN,"hand, hand, hand","hand, hand, hand",quartz,hand,1.000000,0.000000,0.000000,0.000000,0.789474
6592,6592,crystal2/crystal2_13s.jpg,crystal,crystal2,crystal (rock),"lighter, gem, flamethrower, flower, crystal (r...","9850 3144, 16422 22742, 59868, 6411, 5148, 949...",15,6,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",leaves,crystal,0.789474,0.789474,0.093529,0.093529,0.853659
6593,6593,crystal2/crystal2_14s.jpg,crystal,crystal2,crystal (rock),"diamond, crystal (material), diamond, crystal ...","7641, 27351, 8158, 19308, 6273, 4637, 4442, 48...",10,4,4,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",NaN,crystal,0.842105,0.842105,0.083655,0.083655,0.864865
6594,6594,crystal2/crystal2_15s.jpg,crystal,crystal2,crystal (rock),"gem, crystal (material), crystal (material), d...","2797, 51817, 12318, 6240, 57923 4505, 38699, 8...",14,3,4,...,NaN,"amethyst, crystal, crystal, crystal, crystal, ...","amethyst, crystal, crystal, crystal, crystal, ...",counter,crystal,0.611111,0.611111,0.114904,0.114904,0.926829
6595,6595,crystal2/crystal2_16s.jpg,crystal,crystal2,crystal (rock),"crystal (rock), crystal (rock), crystal (mater...","61850, 4460, 3762, 8212 5987, 5439, 9446 4049,...",11,9,9,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",hand,crystal,0.764706,0.764706,0.102879,0.102879,0.717949
6596,6596,crystal2/crystal2_17s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crane (tower crane), cryst...","3722, 16046, 7798, 21122, 4209, 9005, 6927, 81...",19,11,11,...,NaN,"amethyst, candle, crystal, crystal, crystal, c...","amethyst, candle, crystal, crystal, crystal, c...",NaN,crystal,0.631579,0.631579,0.110665,0.110665,0.789474
6597,6597,crystal2/crystal2_18s.jpg,crystal,crystal2,crystal (rock),"diamond, gem, diamond, crystal (material), cry...","7521, 5441, 13204, 19550, 4211, 23762, 3838, 1...",13,2,6,...,NaN,"amethyst, amethyst, amethyst, amethyst, amethy...","amethyst, amethyst, amethyst, amethyst, amethy...",NaN,crystal,0.352941,0.352941,0.115904,0.115904,0.731707
6598,6598,crystal2/crystal2_19s.jpg,crystal,crystal2,crystal (rock),"crystal (material), ice cube, crystal (materia...","57832, 59615, 3576, 69135, 6615, 15335, 9684, ...",13,5,6,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",NaN,crystal,0.789474,0.789474,0.093529,0.093529,0.736842
6599,6599,crystal2/crystal2_20s.jpg,crystal,crystal2,crystal (rock),"crystal (material), crystal (rock), ice cube, ...","9954, 42648, 9553, 34168, 9562, 17828, 13989, ...",14,3,4,...,NaN,"crystal, crystal, crystal, crystal, crystal, c...","crystal, crystal, crystal, crystal, crystal, c...",NaN,crystal,0.705882,0.705882,0.110510,0.110510,0.731707
26560,26560,crystal1.jpg,crystal ball,crystal_ball,crystal ball,"globe (spinning globe), streetlight, tree, cry...","20613, 13397, 47067, 11751, 16829, 48467, 8618...",11,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26561,26561,crystal2.jpg,crystal,crystal1,crystal (material),"jewel, sugar cube, saltshaker, crystal (materi...","10399, 10881, 18635, 18077, 8806, 4709, 6171, ...",16,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26562,26562,crystal_ball.jpg,crystal,crystal2,crystal (rock),"crystal (rock), saltshaker, crystal (material)...","9237, 82862, 12884, 6420, 10417, 52848, 21496,...",12,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Find another concept with an average naming consistency of 0.6068064806875 +/- 0.0002

things_dataset.groupby("Word")["nameability_naming-consistency"].mean().loc[lambda x: (x >= 0.6068064806875 - 0.0002) & (x <= 0.6068064806875 + 0.0002)]

Word
crystal    0.606806
pony       0.606946
Name: nameability_naming-consistency, dtype: float64

In [26]:
get_top_50_concepts(things_dataset=things_dataset)

                 Word  nameability_naming-consistency
767        hobbyhorse                        0.193307
1230           pulpit                        0.323002
1107            patty                        0.361923
1818             yoke                        0.381875
395       cordon bleu                        0.398982
711           gumdrop                        0.417929
1656       tortellini                        0.437276
640           garbage                        0.453328
1253              rag                        0.470846
1068           outfit                        0.486130
298           charger                        0.497988
1213           potpie                        0.509621
1568         swimsuit                        0.531087
357         coat rack                        0.546212
1049              oar                        0.560762
348           clothes                        0.572765
1301           roller                        0.588570
796            hummus                        0.598567
440           crystal                        0.606806
1557          sunroof                        0.620461
1799              wok                        0.634704
1515    station wagon                        0.648714
1801            woman                        0.660846
851            kettle                        0.677771
400         cornbread                        0.693249
407               cot                        0.702504
1031           napkin                        0.719486
635          fur coat                        0.732056
449      curling iron                        0.743979
1270  rearview mirror                        0.761066
496       doorknocker                        0.771653
122            binder                        0.784184
1807   wrapping paper                        0.797005
584     first-aid kit                        0.808528
795       hummingbird                        0.823666
1358            scoop                        0.835471
462              deer                        0.848857
539    electric chair                        0.859749
7              airbag                        0.872060
693            grater                        0.879297
96               bead                        0.889888
647              gate                        0.901633
177     boxing gloves                        0.911311
62             bamboo                        0.920929
439            crutch                        0.933697
924            locker                        0.945259
1534            stool                        0.954410
1059           orange                        0.961524
782             horse                        0.970854
953               map                        0.980343

In [27]:
top_50 = get_top_50_concepts(things_dataset=things_dataset)

top_50

                 Word  nameability_naming-consistency
767        hobbyhorse                        0.193307
1230           pulpit                        0.323002
1107            patty                        0.361923
1818             yoke                        0.381875
395       cordon bleu                        0.398982
711           gumdrop                        0.417929
1656       tortellini                        0.437276
640           garbage                        0.453328
1253              rag                        0.470846
1068           outfit                        0.486130
298           charger                        0.497988
1213           potpie                        0.509621
1568         swimsuit                        0.531087
357         coat rack                        0.546212
1049              oar                        0.560762
348           clothes                        0.572765
1301           roller                        0.588570
796            hummus                        0.598567
440           crystal                        0.606806
1557          sunroof                        0.620461
1799              wok                        0.634704
1515    station wagon                        0.648714
1801            woman                        0.660846
851            kettle                        0.677771
400         cornbread                        0.693249
407               cot                        0.702504
1031           napkin                        0.719486
635          fur coat                        0.732056
449      curling iron                        0.743979
1270  rearview mirror                        0.761066
496       doorknocker                        0.771653
122            binder                        0.784184
1807   wrapping paper                        0.797005
584     first-aid kit                        0.808528
795       hummingbird                        0.823666
1358            scoop                        0.835471
462              deer                        0.848857
539    electric chair                        0.859749
7              airbag                        0.872060
693            grater                        0.879297
96               bead                        0.889888
647              gate                        0.901633
177     boxing gloves                        0.911311
62             bamboo                        0.920929
439            crutch                        0.933697
924            locker                        0.945259
1534            stool                        0.954410
1059           orange                        0.961524
782             horse                        0.970854
953               map                        0.980343

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1410952135.py, line 8)